### ISSUE TITLE
Error when compile with gcc 9

### ISSUE THREAD

**Issue by linuxpham** [bloomberg/corokafka#55]
Hi admin,

### OS : 
Linux heradev 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### GCC/G++ : 
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

### error:

/mnt/data/sources/new_install/corokafka/corokafka/impl/corokafka_consumer_manager_impl.cpp: In static member function ‘static Bloomberg::corokafka::MessageBatch Bloomberg::corokafka::ConsumerManagerImpl::messageBatchReceiveTask(Bloomberg::corokafka::ConsumerTopicEntry&, Bloomberg::corokafka::IoTracker)’:
/mnt/data/sources/new_install/corokafka/corokafka/impl/corokafka_consumer_manager_impl.cpp:977:52: error: missing template arguments before ‘(’ token
  977 |                                  std::move_iterator(tempBatch.begin()),
      |                                                    ^
/mnt/data/sources/new_install/corokafka/corokafka/impl/corokafka_consumer_manager_impl.cpp:978:52: error: missing template arguments before ‘(’ token
  978 |                                  std::move_iterator(tempBatch.end()));
      |                                                    ^
make[2]: *** [corokafka/CMakeFiles/corokafka.dir/build.make:310: corokafka/CMakeFiles/corokafka.dir/impl/corokafka_consumer_manager_impl.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:94: corokafka/CMakeFiles/corokafka.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by accelerated** [comment]
@linuxpham will check and get back to you.

**Comment by accelerated** [comment]
@linuxpham can you please confirm this fixes your problem? ~Thx

**Comment by linuxpham** [comment]
I will check to confirm soon. Thank you so much!

**Comment by linuxpham** [comment]
I try CMAKE with flag: -DCOROKAFKA_ENABLE_TESTS:BOOL=OFF
I still do not compile successfully

/usr/include/gmock/gmock-actions.h:392:27: error: no matching function for call to ‘Apply(const std::function<std::vector<Bloomberg::corokafka::OffsetWatermark>(std::chrono::duration<long int, std::ratio<1, 1000> >)>&, std::remove_reference<std::tuple<std::chrono::duration<long int, std::ratio<1, 1000> > >&>::type)’
  392 |     return internal::Apply(fun_, ::std::move(args));
      |            ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/gmock/gmock-actions.h:51,
